/*
 * Developer API
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v4`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ScanPointConfig
 */


public class ScanPointConfig {
  @SerializedName("scanPointConfigId")
  private Integer scanPointConfigId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("_summary")
  private List<String> _summary = null;

  public ScanPointConfig scanPointConfigId(Integer scanPointConfigId) {
    this.scanPointConfigId = scanPointConfigId;
    return this;
  }

   /**
   * The Scan Point Config ID
   * @return scanPointConfigId
  **/
  @Schema(description = "The Scan Point Config ID")
  public Integer getScanPointConfigId() {
    return scanPointConfigId;
  }

  public void setScanPointConfigId(Integer scanPointConfigId) {
    this.scanPointConfigId = scanPointConfigId;
  }

  public ScanPointConfig name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The Scan Point Config name
   * @return name
  **/
  @Schema(description = "The Scan Point Config name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScanPointConfig _summary(List<String> _summary) {
    this._summary = _summary;
    return this;
  }

  public ScanPointConfig addSummaryItem(String _summaryItem) {
    if (this._summary == null) {
      this._summary = new ArrayList<String>();
    }
    this._summary.add(_summaryItem);
    return this;
  }

   /**
   * The Scan Point Config resrictions described
   * @return _summary
  **/
  @Schema(description = "The Scan Point Config resrictions described")
  public List<String> getSummary() {
    return _summary;
  }

  public void setSummary(List<String> _summary) {
    this._summary = _summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanPointConfig scanPointConfig = (ScanPointConfig) o;
    return Objects.equals(this.scanPointConfigId, scanPointConfig.scanPointConfigId) &&
        Objects.equals(this.name, scanPointConfig.name) &&
        Objects.equals(this._summary, scanPointConfig._summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scanPointConfigId, name, _summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanPointConfig {\n");
    
    sb.append("    scanPointConfigId: ").append(toIndentedString(scanPointConfigId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _summary: ").append(toIndentedString(_summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
