/*
 * Developer API
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v2`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ScanEvent
 */


public class ScanEvent {
  @SerializedName("eventId")
  private Integer eventId = null;

  @SerializedName("scanPointId")
  private Integer scanPointId = null;

  @SerializedName("testMode")
  private Boolean testMode = null;

  public ScanEvent eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * The event ID
   * @return eventId
  **/
  @Schema(description = "The event ID")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public ScanEvent scanPointId(Integer scanPointId) {
    this.scanPointId = scanPointId;
    return this;
  }

   /**
   * The Scan Point ID
   * @return scanPointId
  **/
  @Schema(description = "The Scan Point ID")
  public Integer getScanPointId() {
    return scanPointId;
  }

  public void setScanPointId(Integer scanPointId) {
    this.scanPointId = scanPointId;
  }

  public ScanEvent testMode(Boolean testMode) {
    this.testMode = testMode;
    return this;
  }

   /**
   * True indicates testMode, validate testMode tickets
   * @return testMode
  **/
  @Schema(description = "True indicates testMode, validate testMode tickets")
  public Boolean isTestMode() {
    return testMode;
  }

  public void setTestMode(Boolean testMode) {
    this.testMode = testMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanEvent scanEvent = (ScanEvent) o;
    return Objects.equals(this.eventId, scanEvent.eventId) &&
        Objects.equals(this.scanPointId, scanEvent.scanPointId) &&
        Objects.equals(this.testMode, scanEvent.testMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventId, scanPointId, testMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanEvent {\n");
    
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    scanPointId: ").append(toIndentedString(scanPointId)).append("\n");
    sb.append("    testMode: ").append(toIndentedString(testMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
